name = "nirvana-neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8a2429acf348876bf0fa74c895dd797c55a0ec7a715ea21bde9f3d7738cea3c6"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
