name = "nirvana-fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5e25c01cb0c210ddb427a76844b7e16548dfd455b41ba4abd422633216dac189"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
